name: Deploy to EC2
on:
  push:
    tags:
      - "*"

env:
  DEPLOY_PATH: /var/www/aws-ec2-deploy
  BUILD_PATH: ./backend/dist

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure tag is on main
        run: |
          git fetch origin main --depth=1
          if ! git branch -r --contains "$GITHUB_SHA" | grep -q "origin/main"; then
            echo "Tag commit is not on main. Skipping deployment."
            exit 1
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Install dependencies
        working-directory: backend
        run: npm ci

      - name: Bundle TypeScript project
        run: npm run bundle:backend

      - name: Check SSH connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            echo "SSH connection successful"  
            whoami

      - name: Create target directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            sudo mkdir -p ${{ env.DEPLOY_PATH }}
            sudo chown -R ${{ secrets.EC2_USERNAME }}:${{ secrets.EC2_USERNAME }} ${{ env.DEPLOY_PATH }}

      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: ${{env.BUILD_PATH}}
          target: ${{ env.DEPLOY_PATH }}
          strip_components: 1
          overwrite: true

      - name: Setup and run application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            sudo systemctl reload nginx
            sudo systemctl is-active nginx
            pm2 reload ${{ env.DEPLOY_PATH }}/backend/dist/server.js --name aws-ec2-deploy || pm2 start ${{ env.DEPLOY_PATH }}/backend/dist/server.js --name aws-ec2-deploy
            pm2 save